package com.androimage.booksagar.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class Book extends RealmObject {


    //book_id`,
// `user_id`, `book_title`, `book_author`,
// `book_publisher`, `book_pub_year`, `book_mrp`,
// `book_price`, `book_standard`, `book_language`,
// `book_image`, `noshared`,
// `verified`,
// `added_at`
    @PrimaryKey
    private int id;


    private int seller_id;
    private String title;

    private String author;


    private String publisher;


    private int year;

    private String mrp;

    private String price;

    private String standard;

    private String language;

    private boolean verified;

    private boolean noshared;

    private boolean sold;

    private String imageUrl;


    private String added_on;
    private String description;


    private String type;
    private String location;


    public Book() {

    }

//
//    public Book(long id, String title, String author, String imageUrl) {
//        this.id = id;
//        this.title = title;
//        this.author = author;
//        this.imageUrl = imageUrl;
//    }


    public Book(int id, int seller_id, String title, String author, String publisher, int year, String mrp, String price, String standard, String language, boolean verified, boolean sold, boolean noshared, String added_on, String imageUrl, String description, String location, String type) {
        this.id = id;
        this.seller_id = seller_id;
        this.title = title;
        this.author = author;
        this.publisher = publisher;
        this.year = year;
        this.mrp = mrp;
        this.price = price;
        this.sold = sold;
        this.standard = standard;
        this.language = language;
        this.verified = verified;
        this.noshared = noshared;
        this.imageUrl = imageUrl;
        this.description = description;
        this.type = type;
        this.location = location;


        try {
            SimpleDateFormat fromUser = new SimpleDateFormat("yyyy-MM-dd");


            SimpleDateFormat formatter = new SimpleDateFormat("MMM dd yyyy");
            this.added_on = formatter.format(fromUser.parse(added_on.substring(0, 9)));
        } catch (ParseException e) {
            e.printStackTrace();
        }

    }

    // Standard getters & setters generated by your IDE…
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }


    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getAdded_on() {
        return added_on;
    }

    public void setAdded_on(String added_on) {
        this.added_on = added_on;
    }

    public String getMrp() {
        return mrp;
    }

    public void setMrp(String mrp) {
        this.mrp = mrp;
    }

    public int getSeller_id() {
        return seller_id;
    }

    public void setSeller_id(int seller_id) {
        this.seller_id = seller_id;
    }

    public String getPrice() {
        return price;
    }


    public void setPrice(String price) {
        this.price = price;
    }

    public String getStandard() {
        return standard;
    }

    public void setStandard(String standard) {
        this.standard = standard;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public boolean isVerified() {
        return verified;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    public boolean isSold() {
        return sold;
    }

    public void setSold(boolean sold) {
        this.sold = sold;
    }

    public boolean isNoshared() {
        return noshared;
    }

    public void setNoshared(boolean noshared) {
        this.noshared = noshared;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

}

